### ISSUE TITLE
The SpringBoot project built by Gradle dependency the okhttp 4.x version (upgrade version) after the component is config, and an error is reported when compiling

### ISSUE THREAD

**Issue by xingguang2013** [Ahoo-Wang/CosId#97] opened 2022-05-20 01:42 UTC
## Bug Report

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/Ahoo-Wang/CosId/issues).
- Read documentation: [CosId Doc](https://cosid.ahoo.me/).

Please pay attention on issues you submitted, because we maybe need more details.
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of CosId did you use?
1.10.2
### Expected behavior
Gradle build succeeded
### Actual behavior
Gradle build error

```shell
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.squareup.okhttp3:okhttp:3.14.9.
     Required by:
         project : > me.ahoo.cosid:cosid-core:1.10.2 > me.ahoo.cosid:cosid-dependencies:1.10.2
      > No matching variant of com.squareup.okhttp3:okhttp:4.9.3 was found. The consumer was configured to find an API of a component compatible with Java 11, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.gradle.category' with value 'platform' but:
          - Variant 'apiElements' capability com.squareup.okhttp3:okhttp:4.9.3 declares an API of a component compatible with Java 8, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, as well as attribute 'org.gradle.category' with value 'library' and the consumer needed a component, as well as attribute 'org.gradle.category' with value 'platform'
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'javadocElements' capability com.squareup.okhttp3:okhttp:4.9.3 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares a component, as well as attribute 'org.gradle.category' with value 'documentation' and the consumer needed a component, as well as attribute 'org.gradle.category' with value 'platform'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
          - Variant 'runtimeElements' capability com.squareup.okhttp3:okhttp:4.9.3 declares a runtime of a component compatible with Java 8, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, as well as attribute 'org.gradle.category' with value 'library' and the consumer needed a component, as well as attribute 'org.gradle.category' with value 'platform'
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'sourcesElements' capability com.squareup.okhttp3:okhttp:4.9.3 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares a component, as well as attribute 'org.gradle.category' with value 'documentation' and the consumer needed a component, as well as attribute 'org.gradle.category' with value 'platform'
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
2 actionable tasks: 1 executed, 1 up-to-date
```

### Steps to reproduce the behavior
execute `gradle clean build -x test`
### Example codes for reproduce this issue (such as a github link).
```groovy
ext {
    set('springCloudVersion', "2021.0.2")
    set('cosidVersion', '1.10.2')
    set('okhttpVersionn', '4.9.3')
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'

    implementation 'me.ahoo.cosid:cosid-core'
    implementation 'me.ahoo.cosid:cosid-jackson'
    implementation 'me.ahoo.cosid:cosid-jdbc'
    implementation 'me.ahoo.cosid:cosid-mybatis'
    implementation 'me.ahoo.cosid:cosid-redis'
    implementation 'me.ahoo.cosid:cosid-shardingsphere'
    implementation 'me.ahoo.cosid:cosid-spring-boot-starter'
    implementation 'me.ahoo.cosid:cosid-spring-redis'
    implementation 'me.ahoo.cosid:cosid-zookeeper'

    implementation "com.squareup.okhttp3:okhttp:${okhttpVersionn}"
}
```

**Comment by Ahoo-Wang** [comment] 2022-05-20 02:34
Thanks a lot for your feedback. I've fixed the issue and the `1.10.3` version will be released when CI is complete.

**Comment by Ahoo-Wang** [comment] 2022-05-20 02:37
From the point of view of your dependency import, you don't need to import so many `cosid` modules.
These dependencies are optional,You just need to choose one of them:
- implementation 'me.ahoo.cosid:cosid-jdbc'
- implementation 'me.ahoo.cosid:cosid-redis'
- implementation 'me.ahoo.cosid:cosid-spring-redis'
- implementation 'me.ahoo.cosid:cosid-zookeeper'

You can refer to [examples](https://github.com/Ahoo-Wang/CosId/tree/main/examples) to get started quickly.

**Comment by xingguang2013** [comment] 2022-05-20 02:38
I will try to verify as soon as the maven repository is available for download, thanks a lot

**Comment by Ahoo-Wang** [comment] 2022-05-20 02:43
Synchronization of the central repository is very slow. You can install the package to your local repository using:
- `git clone https://github.com/Ahoo-Wang/CosId.git`
- `cd CosId`
-  `gradle publishToMavenLocal`

**Comment by xingguang2013** [comment] 2022-05-20 03:08
It has been verified that Gradle compiles through, Gradle build success, Can you explain why, I don't understand

**Comment by Ahoo-Wang** [comment] 2022-05-20 03:18
Caused by the wrong way of importing dependencies.Here's a comparison of the before and after changes:
https://github.com/Ahoo-Wang/CosId/commit/36eb2d45c848ccc41d1076076b7ab0b6e5fc6001
The following is the POM file generated by `1.0.2`:
https://repo1.maven.org/maven2/me/ahoo/cosid/cosid-dependencies/1.10.2/cosid-dependencies-1.10.2.pom
```xml
<dependency>
  <groupId>com.squareup.okhttp3</groupId>
  <artifactId>okhttp</artifactId>
  <version>3.14.9</version>
  <type>pom</type>
  <scope>import</scope>
</dependency>
```
The following is the POM file generated by `1.0.3`:

https://oss.sonatype.org/service/local/repositories/releases/content/me/ahoo/cosid/cosid-dependencies/1.10.3/cosid-dependencies-1.10.3.pom

**Comment by xingguang2013** [comment] 2022-05-20 03:23
thanks

**Closed** 2022-05-20 03:56 UTC
Labels: good first issue, dependency
